export interface ManagedProduct {
  id: string;
  name: string;
  image: string;
  description: string;
  price: string;
  acceptOrders: boolean;
  todayAvailable: boolean;
  dailyMax: number;
  prepDays: number;
  category: string;
  maxPerOrder: number;
}

export const managedProducts: ManagedProduct[] = [
  {
    id: "1",
    name: "カスタードプリン",
    image: "https://images.pexels.com/photos/2638026/pexels-photo-2638026.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "なめらかでとろけるような口あたりと、ほどよい甘さのカラメルソース...",
    price: "¥390",
    acceptOrders: true,
    todayAvailable: true,
    dailyMax: 30,
    prepDays: 0,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "2",
    name: "ロールケーキ",
    image: "https://images.pexels.com/photos/1721932/pexels-photo-1721932.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "ふんわり焼き上げたスポンジで、なめらかな生クリームをやさしく巻き上...",
    price: "¥500",
    acceptOrders: true,
    todayAvailable: true,
    dailyMax: 30,
    prepDays: 0,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "3",
    name: "チーズケーキ",
    image: "https://images.pexels.com/photos/1126359/pexels-photo-1126359.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "クリームチーズをたっぷり使い、なめらかに焼き上げたベイクドチーズケ...",
    price: "¥600",
    acceptOrders: true,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "4",
    name: "抹茶ケーキ",
    image: "https://images.pexels.com/photos/4109998/pexels-photo-4109998.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "香り高い宇治抹茶を贅沢に使った抹茶ケーキ。ほろ苦さと甘さのバランス...",
    price: "¥600",
    acceptOrders: true,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "5",
    name: "期間限定　テスト",
    image: "https://images.pexels.com/photos/3026804/pexels-photo-3026804.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "期間限定商品です",
    price: "¥600",
    acceptOrders: true,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "期間限定",
    maxPerOrder: 10,
  },
  {
    id: "6",
    name: "チョコレートケーキ",
    image: "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "濃厚でしっとりとしたチョコレート生地に、ビターなガナッシュを合わせ...",
    price: "¥650",
    acceptOrders: true,
    todayAvailable: true,
    dailyMax: 30,
    prepDays: 0,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "7",
    name: "ショートケーキ",
    image: "https://images.pexels.com/photos/1854652/pexels-photo-1854652.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "ふわふわのスポンジに、ほどよい甘さの生クリームと新鮮ないちごを重ね...",
    price: "¥700",
    acceptOrders: true,
    todayAvailable: true,
    dailyMax: 30,
    prepDays: 10,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "8",
    name: "マドレーヌ",
    image: "https://images.pexels.com/photos/3992134/pexels-photo-3992134.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "外はこんがり、内はしっとり。ひとつひとつ丁寧に焼き上げた、バターの...",
    price: "¥350",
    acceptOrders: true,
    todayAvailable: true,
    dailyMax: 30,
    prepDays: 0,
    category: "焼き菓子",
    maxPerOrder: 10,
  },
  {
    id: "9",
    name: "マフィン",
    image: "https://images.pexels.com/photos/1855135/pexels-photo-1855135.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "外はこんがり、内はふんわり。素材の香りを大切に、ひとつひとつ丁寧に...",
    price: "¥350",
    acceptOrders: true,
    todayAvailable: true,
    dailyMax: 30,
    prepDays: 0,
    category: "焼き菓子",
    maxPerOrder: 10,
  },
  {
    id: "10",
    name: "プリントデコ",
    image: "https://images.pexels.com/photos/1702373/pexels-photo-1702373.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "プリントデコ",
    price: "+¥1,500",
    acceptOrders: true,
    todayAvailable: true,
    dailyMax: 30,
    prepDays: 7,
    category: "その他",
    maxPerOrder: 10,
  },
  {
    id: "11",
    name: "ショコラ",
    image: "https://images.pexels.com/photos/1854652/pexels-photo-1854652.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "濃厚でなめらかなチョコレートの口どけを堪能できる、贅沢なホールケー...",
    price: "¥4,000~",
    acceptOrders: true,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "ホール",
    maxPerOrder: 10,
  },
  {
    id: "12",
    name: "焼き菓子セット",
    image: "https://images.pexels.com/photos/3992134/pexels-photo-3992134.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "焼き菓子のセットです",
    price: "¥5,000",
    acceptOrders: true,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 5,
    category: "焼き菓子",
    maxPerOrder: 10,
  },
  {
    id: "13",
    name: "シュークリーム",
    image: "https://images.pexels.com/photos/2638026/pexels-photo-2638026.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "パティモバ洋菓子店の看板メニューです。",
    price: "¥400",
    acceptOrders: false,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "14",
    name: "レモンタルト",
    image: "https://images.pexels.com/photos/3026804/pexels-photo-3026804.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "爽やかな酸味とやさしい甘さが調和した、当店自慢のレモンタルト。しっ...",
    price: "¥600",
    acceptOrders: false,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "15",
    name: "Today's Cake",
    image: "https://images.pexels.com/photos/1854652/pexels-photo-1854652.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "本日のおすすめケーキ",
    price: "¥700",
    acceptOrders: false,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "16",
    name: "期間限定(2)",
    image: "https://images.pexels.com/photos/1702373/pexels-photo-1702373.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "期間限定商品その2です",
    price: "¥800",
    acceptOrders: false,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "期間限定",
    maxPerOrder: 10,
  },
  {
    id: "17",
    name: "クッキーの詰め合わせ",
    image: "https://images.pexels.com/photos/3992134/pexels-photo-3992134.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "バニラ、チョコチップ、ジャムサンド、ショコラなど、バラエティ豊か...",
    price: "¥2,200",
    acceptOrders: false,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "焼き菓子",
    maxPerOrder: 10,
  },
  {
    id: "18",
    name: "モンブラン",
    image: "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "やさしい甘さのマロンペーストに、さくっとしたメレンゲと生クリームを...",
    price: "¥600",
    acceptOrders: false,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "生菓子",
    maxPerOrder: 10,
  },
  {
    id: "19",
    name: "クリスマスケーキ",
    image: "https://images.pexels.com/photos/1854652/pexels-photo-1854652.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "クリスマス限定の特別なケーキです",
    price: "¥5,000",
    acceptOrders: false,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 0,
    category: "ホール",
    maxPerOrder: 10,
  },
  {
    id: "20",
    name: "ホールケーキ",
    image: "https://images.pexels.com/photos/1854652/pexels-photo-1854652.jpeg?auto=compress&cs=tinysrgb&w=80",
    description: "しっとりと焼き上げたスポンジに、口どけの良い生クリームをたっぷりと...",
    price: "+",
    acceptOrders: false,
    todayAvailable: false,
    dailyMax: 30,
    prepDays: 1,
    category: "ホール",
    maxPerOrder: 10,
  },
];

export const cakeCategories = ["生菓子", "焼き菓子", "ホール", "期間限定", "ドリンク", "その他"];
